Dom menu
Pazzo97/Portfolio-project pull request #15
Opened 2022-04-04 19:35 UTC by Pazzo97

Added DOM to portfolio project

2022-04-04 20:21 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Pazzo97 and Team👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
- [ ] This branch has conflicts with the base branch, Please fix the conflicts. This can help you [Resolve GitHub conflicts ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github).

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-04 20:21 UTC, thecodechaser commented on style.css
> +
- [ ] Good job on the design but for this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A2925) design as much as possible. Please reduce the top margin of your mobile menu, Use the correct font size, and font-weight and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/161624074-77af5f09-7cfb-406c-abc6-45c30d8fcb87.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161623996-d00378d9-b07e-4663-8c12-f01dcd3c3612.png)

2022-04-04 20:21 UTC, thecodechaser commented on style.css
> +  }
- [ ] Please use the correct size for your close(X) button, and make sure it matches the design on the template.

### Your design

![image](https://user-images.githubusercontent.com/83803414/161624896-5adeccda-4e73-47a9-9e7f-0b124a841026.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/161624877-5073f0d0-0052-4b17-b0e6-29f65b3c6c48.png)

2022-04-05 08:11 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Pazzo97** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- When the user clicks the hamburger button, the mobile menu appears.✔️ 
- When the user clicks the close button, the mobile menu disappear.✔️ 
- When the user clicks any of the mobile menu options, a correct part of the page is displayed.✔️ 
- When the user clicks any option of the mobile menu, the mobile menu disappear.✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


- [OPTIONAL ] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)



Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 08:29 UTC, merged