Added pop window css
Pazzo97/Portfolio-project pull request #18
Opened 2022-04-05 18:04 UTC by Pazzo97

This PR is about pop up window on portfolio project

2022-04-05 20:21 UTC, micheaol requested changes
Hi @Pazzo97 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-05 20:21 UTC, micheaol commented on index.html
> +
Please ensure that the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads).

2022-04-06 08:06 UTC, prolajumokeoni approved these changes
Hi @Pazzo97 👋🏿 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 08:12 UTC, prolajumokeoni commented on index.js
> +    // eslint-disable-next-line no-use-before-define
- [ ] Kindly avoid disabling linters in your project as this is bad practice, always fix linter errors and ensure all checks are green 👍🏿

2022-04-06 08:18 UTC, merged